### ISSUE TITLE
Please add 'cancel' option

### ISSUE THREAD

**Issue by aashh** [lgaches/BrowserPrompt#2]
Sometimes a link is accidentally clicked, or an unwanted URL is opened by an application. In these cases, it would be useful for BrowserPrompt to offer a 'cancel' option. I humbly suggest ⌘0.

**Comment by lgaches** [comment]
Thank you for the feedback. If you click anywhere outside BrowserPrompt window, BrowserPrompt will be dismissed. 
In the next release ⌘0 also will cancel the action.

**Comment by lgaches** [comment]
@aashh you can download the beta version ([here](https://testflight.apple.com/join/p8KILb90)). Browser Prompt window can be closed with the close button of ⌘w.
