### ISSUE TITLE
Adding Edge Browser to the default list

### ISSUE THREAD

**Issue by nepetro** [lgaches/BrowserPrompt#3]
Greetings! Currently Browser Prompt has most of my browsers listed, but its missing Edge (and includes Zoom which I won't need). How can I add Edge and remove Zoom? Thanks!

**Comment by lgaches** [comment]
Hi @nepetro. We will add more browser supports in the next release and will add a possibility to hide browsers.

**Comment by lgaches** [comment]
@nepetro  TestFlight build with Edge supports is available. You can now also disable the browser you don't want to use in the Settings screen.
[TestFlight](https://testflight.apple.com/join/p8KILb90)
