### ISSUE TITLE
Wishlist: add "copy URL" function

### ISSUE THREAD

**Issue by aashh** [lgaches/BrowserPrompt#4]
Some applications lack a good function for copying a URL to the pasteboard. I think it would be useful for some users if BrowserPrompt offered ⌘C as an action.

**Comment by lgaches** [comment]
@aashh  A new build supporting ⌘C is available. Let me know if it's working for you.
[TestFlight](https://testflight.apple.com/join/p8KILb90)

**Comment by aashh** [comment]
@lgaches Thank you, it works for me on macOS 12.5.1 (arm) !

It would be nice if the UI provided some feedback that the 'copy' occurred. Right now I don't see any.

**Comment by aashh** [comment]
I noticed that clicking on the URL in the BrowserPrompt also copies it, and this is confirmed by the URL changing color. This seems like it would also work well as confirmation of ⌘C.

**Comment by lgaches** [comment]
@aashh thanks for the feedback. A new build with UI feedback on ⌘C  is available.

**Comment by lgaches** [comment]
a new version is available on the AppStore
